### ISSUE TITLE
In-guide formatting (source)

### ISSUE THREAD

**Issue by drussell393** [TheTechShed/Guides#2]
The following **should** be a thing:

- Notes
- Caution/Warnings
- File Excerpts
- Table Styles
- Image inclusion
- Code block

Now, the question is, how do we want to format such things? We could go with the basic CMS markdown way of doing it. For example:

{note}

Or:

[note]

Or:

{.note:}

Any comments on this?

**Comment by drussell393** [comment]
Personally, I'm apt to choose tags:

[note] Infos [/note]

[code] Infos [/code]

and so on..

**Comment by Joeltrane** [comment]
I guess we will be using wiki syntax instead then?

**Comment by drussell393** [comment]
I'm almost tempted to do tags...

**Comment by drussell393** [comment]
So, we're going to do tags on this one. Easier to parse with the custom CMS, and more natural imo. Will reopen if anyone disagrees, but closing.
