### ISSUE TITLE
Wrapping Text in Guides

### ISSUE THREAD

**Issue by drussell393** [TheTechShed/Guides#3]
Pretty easy question, open for discussion. Should we wrap text in guides, or let it go on for miles? I'm all about making something look nice, making it easy to read even in the git diff, and without wrapped text this becomes a bit messy on GitHub's file history log.

**Comment by Joeltrane** [comment]
I do like wrapping, however, for purposes such as this, I think that requiring use of the \ to break lines may be better for those copy and paste moments.... I mean individuals. I am speaking strictly of commands and not body text of a document. Please clarify which class of text you would prefer to be wrapped?

**Comment by drussell393** [comment]
Do what... you don't need \ in Markdown. 

And all text would be wrapped at X characters. I usually go with 60.

**Comment by Joeltrane** [comment]
Right, so you were referring to the entire document. Yes, I think wrapping is the best option.

**Comment by drussell393** [comment]
Wrapping will be required in the formatting guide moving forward. We're going to hard wrap at 60 - 65 characters for consistency.
